apiVersion: v1
kind: Pod
metadata:
  name: postgres-db
  namespace: hera
spec:
  containers:
    - name: postgres-container
      image: postgres:latest
      env:
        - name: POSTGRES_DB
          value: students
        - name: POSTGRES_USER
          value: htahreem
        - name: POSTGRES_PASSWORD
          value: Cloudera2024
