apiVersion: apps/v1
kind: Deployment
metadata:
  name: demogolang-service
  namespace: hera
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demogolang-service
  template:
    metadata:
      labels:
        app: demogolang-service
    spec:
      containers:
        - name: demogolang-service
          image: docker-sandbox.infra.cloudera.com/htahreem/demo-image
          ports:
            - containerPort: 8001
          env:
            - name: DB_HOST
              value: postgres-service.hera.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: htahreem
            - name: DB_PASSWORD
              value: Cloudera2024
            - name: DB_NAME
              value: students
      nodeSelector:
        kubernetes.io/hostname: worker-27.shared-rke-dev-01.kcloud.cloudera.com       

