apiVersion: v1
kind: Service
metadata:
  name: demopostgres-service
  namespace: hera
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
