version: '3'

services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: students
      POSTGRES_USER: htahreem
      POSTGRES_PASSWORD: Cloudera2024
