apiVersion: v1
kind: Service
metadata:
  name: task-3-service
  namespace: hera
spec:
  selector:
    app: task-3
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
