apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-server
  template:
    metadata:
      labels:
        app: golang-server
    spec:
      containers:
      - name: golang-server
        image: docker-sandbox.infra.cloudera.com/htahreem/backend
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: golang-service
spec:
  selector:
    app: golang-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
